name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy'
        required: true
        type: choice
        options:
          - development
          - production

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Terraform Plan (${{ inputs.environment }})
    runs-on: self-hosted
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    defaults:
      run:
        working-directory: environments/${{ inputs.environment }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Init
        run: terraform init

      - name: Format Check
        run: terraform fmt -check

      - name: Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: environments/${{ inputs.environment }}/tfplan

  apply:
    name: Terraform Apply (${{ inputs.environment }})
    needs: plan
    runs-on: self-hosted
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    environment:
      name: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: environments/${{ inputs.environment }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Init
        run: terraform init

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: environments/${{ inputs.environment }}

      - name: Terraform Apply
        run: terraform apply tfplan
